In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline

In [2]:
data=pd.read_csv('Reviews.csv')

In [3]:
data.head(10)

Id   ProductId          UserId                      ProfileName  \
0   1  B001E4KFG0  A3SGXH7AUHU8GW                       delmartian   
1   2  B00813GRG4  A1D87F6ZCVE5NK                           dll pa   
2   3  B000LQOCH0   ABXLMWJIXXAIN  Natalia Corres "Natalia Corres"   
3   4  B000UA0QIQ  A395BORC6FGVXV                             Karl   
4   5  B006K2ZZ7K  A1UQRSCLF8GW1T    Michael D. Bigham "M. Wassir"   
5   6  B006K2ZZ7K   ADT0SRK1MGOEU                   Twoapennything   
6   7  B006K2ZZ7K  A1SP2KVKFXXRU1                David C. Sullivan   
7   8  B006K2ZZ7K  A3JRGQVEQN31IQ               Pamela G. Williams   
8   9  B000E7L2R4  A1MZYO9TZK0BBI                         R. James   
9  10  B00171APVA  A21BT40VZCCYT4                    Carol A. Reed   

   HelpfulnessNumerator  HelpfulnessDenominator  Score        Time  \
0                     1                       1      5  1303862400   
1                     0                       0      1  1346976000   
2                     1                       1      4  1219017600   
3                     3                       3      2  1307923200   
4                     0                       0      5  1350777600   
5                     0                       0      4  1342051200   
6                     0                       0      5  1340150400   
7                     0                       0      5  1336003200   
8                     1                       1      5  1322006400   
9                     0                       0      5  1351209600   

                                         Summary  \
0                          Good Quality Dog Food   
1                              Not as Advertised   
2                          "Delight" says it all   
3                                 Cough Medicine   
4                                    Great taffy   
5                                     Nice Taffy   
6  Great!  Just as good as the expensive brands!   
7                         Wonderful, tasty taffy   
8                                     Yay Barley   
9                               Healthy Dog Food   

                                                Text  
0  I have bought several of the Vitality canned d...  
1  Product arrived labeled as Jumbo Salted Peanut...  
2  This is a confection that has been around a fe...  
3  If you are looking for the secret ingredient i...  
4  Great taffy at a great price.  There was a wid...  
5  I got a wild hair for taffy and ordered this f...  
6  This saltwater taffy had great flavors and was...  
7  This taffy is so good.  It is very soft and ch...  
8  Right now I'm mostly just sprouting this so my...  
9  This is a very healthy dog food. Good for thei...

In [4]:
data.shape

(568454, 10)

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 568454 entries, 0 to 568453
Data columns (total 10 columns):
Id                        568454 non-null int64
ProductId                 568454 non-null object
UserId                    568454 non-null object
ProfileName               568438 non-null object
HelpfulnessNumerator      568454 non-null int64
HelpfulnessDenominator    568454 non-null int64
Score                     568454 non-null int64
Time                      568454 non-null int64
Summary                   568427 non-null object
Text                      568454 non-null object
dtypes: int64(5), object(5)
memory usage: 43.4+ MB


In [6]:
data.describe()

Id  HelpfulnessNumerator  HelpfulnessDenominator  \
count  568454.000000         568454.000000            568454.00000   
mean   284227.500000              1.743817                 2.22881   
std    164098.679298              7.636513                 8.28974   
min         1.000000              0.000000                 0.00000   
25%    142114.250000              0.000000                 0.00000   
50%    284227.500000              0.000000                 1.00000   
75%    426340.750000              2.000000                 2.00000   
max    568454.000000            866.000000               923.00000   

               Score          Time  
count  568454.000000  5.684540e+05  
mean        4.183199  1.296257e+09  
std         1.310436  4.804331e+07  
min         1.000000  9.393408e+08  
25%         4.000000  1.271290e+09  
50%         5.000000  1.311120e+09  
75%         5.000000  1.332720e+09  
max         5.000000  1.351210e+09

In [7]:
food=data[['Text','Score']]

In [8]:
food.head(10)

Text  Score
0  I have bought several of the Vitality canned d...      5
1  Product arrived labeled as Jumbo Salted Peanut...      1
2  This is a confection that has been around a fe...      4
3  If you are looking for the secret ingredient i...      2
4  Great taffy at a great price.  There was a wid...      5
5  I got a wild hair for taffy and ordered this f...      4
6  This saltwater taffy had great flavors and was...      5
7  This taffy is so good.  It is very soft and ch...      5
8  Right now I'm mostly just sprouting this so my...      5
9  This is a very healthy dog food. Good for thei...      5

In [9]:
from sklearn.feature_extraction.text import CountVectorizer

In [10]:
#X_train_counts = count_vect.fit_transform(data.Text)

In [11]:
#X_train_counts.shape

In [83]:
X=data.Text[:1000]

In [82]:
X

0      I have bought several of the Vitality canned d...
1      Product arrived labeled as Jumbo Salted Peanut...
2      This is a confection that has been around a fe...
3      If you are looking for the secret ingredient i...
4      Great taffy at a great price.  There was a wid...
5      I got a wild hair for taffy and ordered this f...
6      This saltwater taffy had great flavors and was...
7      This taffy is so good.  It is very soft and ch...
8      Right now I'm mostly just sprouting this so my...
9      This is a very healthy dog food. Good for thei...
10     I don't know if it's the cactus or the tequila...
11     One of my boys needed to lose some weight and ...
12     My cats have been happily eating Felidae Plati...
13     good flavor! these came securely packed... the...
14     The Strawberry Twizzlers are my guilty pleasur...
15     My daughter loves twizzlers and this shipment ...
16     I love eating them and they are good for watch...
17     I am very satisfied with

In [81]:
X[1]

'Product arrived labeled as Jumbo Salted Peanuts...the peanuts were actually small sized unsalted. Not sure if this was an error or if the vendor intended to represent the product as "Jumbo".'

In [15]:
y=data.Score[:1000]

In [16]:
y

0      5
1      1
2      4
3      2
4      5
5      4
6      5
7      5
8      5
9      5
10     5
11     5
12     1
13     4
14     5
15     5
16     2
17     5
18     5
19     5
20     5
21     5
22     5
23     5
24     5
25     5
26     1
27     4
28     5
29     5
      ..
970    5
971    5
972    5
973    5
974    4
975    5
976    4
977    5
978    5
979    5
980    5
981    5
982    5
983    5
984    5
985    5
986    5
987    5
988    5
989    5
990    5
991    5
992    5
993    5
994    5
995    5
996    5
997    5
998    1
999    2
Name: Score, Length: 1000, dtype: int64

In [17]:
y.head(5)

0    5
1    1
2    4
3    2
4    5
Name: Score, dtype: int64

In [18]:
from sklearn.cross_validation import train_test_split

/home/kiran/.local/lib/python3.5/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [19]:
X_train,X_test,y_train,y_test=train_test_split(X,y ,random_state=1)

In [20]:
X_train.shape

(750,)

In [21]:
X_test.shape

(250,)

In [22]:
y_train.shape

(750,)

In [23]:
y_test.shape

(250,)

In [24]:
count_vect=CountVectorizer()

In [25]:
count_vect

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [26]:
count_vect.fit(X_train)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [27]:
X_train_dtm=count_vect.transform(X_train)

In [28]:
X_train_dtm

<750x5143 sparse matrix of type '<class 'numpy.int64'>'
	with 37712 stored elements in Compressed Sparse Row format>

In [29]:
X_test_dtm=count_vect.transform(X_test)

In [30]:
X_test_dtm

<250x5143 sparse matrix of type '<class 'numpy.int64'>'
	with 11660 stored elements in Compressed Sparse Row format>

In [86]:
X_train_dtm=count_vect.fit_transform(X_train)

In [85]:
pd.DataFrame(X_train_dtm.toarray(),columns=count_vect.get_feature_names())

00  000  000kwh  042608460503  0472066978  0738551856  09  0g  0mg  0z  \
0     0    0       0             0           0           0   0   0    0   0   
1     0    0       0             0           0           0   0   0    0   0   
2     0    0       0             0           0           0   0   0    0   0   
3     0    0       0             0           0           0   0   0    0   0   
4     0    0       0             0           0           0   0   0    0   0   
5     0    0       0             0           0           0   0   0    0   0   
6     0    0       0             0           0           0   0   0    0   0   
7     0    0       0             0           0           0   0   0    0   0   
8     0    0       0             0           0           0   0   0    0   0   
9     0    0       0             0           0           0   0   0    0   0   
10    0    0       0             0           0           0   0   0    0   0   
11    0    0       0             0           0           0   0   0    0   0   
12    0    0       0             0           0           0   0   0    0   0   
13    0    0       0             0           0           0   0   0    0   0   
14    0    0       0             0           0           0   0   0    0   0   
15    0    0       0             0           0           0   0   0    0   0   
16    0    0       0             0           0           0   0   0    0   0   
17    0    0       0             0           0           0   0   0    0   0   
18    0    0       0             0           0           0   0   0    0   0   
19    0    0       0             0           0           0   0   0    0   0   
20    0    0       0             0           0           0   0   0    0   0   
21    0    0       0             0           0           0   0   0    0   0   
22    0    0       0             0           0           0   0   0    0   0   
23    0    0       0             0           0           0   0   0    0   0   
24    0    0       0             0           0           0   0   0    0   0   
25    0    0       0             0           0           0   0   0    0   0   
26    0    0       0             0           0           0   0   0    0   0   
27    0    0       0             0           0           0   0   0    0   0   
28    0    0       0             0           0           0   0   0    0   0   
29    0    0       0             0           0           0   0   0    0   0   
..   ..  ...     ...           ...         ...         ...  ..  ..  ...  ..   
720   0    0       0             0           0           0   0   0    0   0   
721   0    0       0             0           0           0   0   0    0   0   
722   0    0       0             0           0           0   0   0    0   0   
723   0    0       0             0           0           0   0   0    0   0   
724   0    0       0             0           0           0   0   0    0   0   
725   0    0       0             0           0           0   0   0    0   0   
726   0    0       0             0           0           0   0   0    0   0   
727   0    0       0             0           0           0   0   0    0   0   
728   0    0       0             0           0           0   0   0    0   0   
729   0    0       0             0           0           0   0   0    0   0   
730   0    0       0             0           0           0   0   0    0   0   
731   0    0       0             0           0           0   0   0    0   0   
732   0    0       0             0           0           0   0   0    0   0   
733   0    0       0             0           0           0   0   0    0   0   
734   0    0       0             0           0           0   0   0    0   0   
735   0    0       0             0           0           0   0   0    0   0   
736   0    0       0             0           0           0   0   0    0   0   
737   0    0       0             0           0           0   0   0    0   0   
738   0    0       0             0           0         

The multinomial Naive Bayes classifier is suitable for classification with discrete features (e.g., word counts for text classification). The multinomial distribution normally requires integer feature counts. However, in practice, fractional counts such as tf-idf may also work.

In [43]:
from sklearn.naive_bayes import MultinomialNB

In [44]:
nb=MultinomialNB()

In [45]:
nb

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [46]:
%time nb.fit(X_train_dtm,y_train)

CPU times: user 3.55 ms, sys: 0 ns, total: 3.55 ms
Wall time: 3.28 ms


MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [47]:
#make class predictions for (X_test_dtm)
y_pred_class=nb.predict(X_test_dtm)

In [48]:
y_pred_class

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       4, 5, 5, 5, 5, 5, 5, 5])

In [49]:
#calculate accuracy of class predictions
from sklearn import metrics

In [50]:
metrics.accuracy_score(y_test,y_pred_class)

0.648

In [51]:
#print the confusion matrix
metrics.confusion_matrix(y_test,y_pred_class)

array([[  1,   0,   0,   0,  27],
       [  0,   0,   0,   0,  10],
       [  0,   0,   0,   0,  15],
       [  0,   0,   0,   0,  35],
       [  0,   0,   0,   1, 161]])

# #tfidf TfidfVectorizer (term frequency -inverse document frequency)

In [52]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [53]:
tf = TfidfVectorizer()

In [54]:
tf

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), norm='l2', preprocessor=None, smooth_idf=True,
        stop_words=None, strip_accents=None, sublinear_tf=False,
        token_pattern='(?u)\\b\\w\\w+\\b', tokenizer=None, use_idf=True,
        vocabulary=None)

In [55]:
tf = TfidfVectorizer(stop_words='english')

In [56]:
tf

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), norm='l2', preprocessor=None, smooth_idf=True,
        stop_words='english', strip_accents=None, sublinear_tf=False,
        token_pattern='(?u)\\b\\w\\w+\\b', tokenizer=None, use_idf=True,
        vocabulary=None)

In [76]:
tf.fit(X_train,y_train)

HashingVectorizer(alternate_sign=True, analyzer='word', binary=False,
         decode_error='strict', dtype=<class 'numpy.float64'>,
         encoding='utf-8', input='content', lowercase=True,
         n_features=1000, ngram_range=(1, 1), non_negative=False,
         norm='l2', preprocessor=None, stop_words=None, strip_accents=None,
         token_pattern='(?u)\\b\\w\\w+\\b', tokenizer=None)

In [77]:
tf

HashingVectorizer(alternate_sign=True, analyzer='word', binary=False,
         decode_error='strict', dtype=<class 'numpy.float64'>,
         encoding='utf-8', input='content', lowercase=True,
         n_features=1000, ngram_range=(1, 1), non_negative=False,
         norm='l2', preprocessor=None, stop_words=None, strip_accents=None,
         token_pattern='(?u)\\b\\w\\w+\\b', tokenizer=None)

In [58]:
tf.vocabulary_

{'instructions': 2299,
 'posters': 3284,
 'beat': 471,
 'aluminum': 256,
 'coloring': 953,
 'cleaned': 906,
 '2338': 53,
 'cradle': 1107,
 'slimy': 3940,
 'meats': 2726,
 'discourage': 1360,
 'rootbeer': 3660,
 'solve': 3988,
 'cracked': 1103,
 'result': 3590,
 'b000aqpmha': 394,
 'foods': 1802,
 '16': 28,
 'alternative': 252,
 'reserve': 3577,
 'tested': 4376,
 'continued': 1052,
 'oilive': 2989,
 'pain': 3097,
 'recipe': 3489,
 'crystalize': 1162,
 'options': 3023,
 'pleased': 3235,
 'benefits': 494,
 'twist': 4549,
 'positive': 3278,
 'spiced': 4047,
 'yo': 4852,
 'poorly': 3263,
 'b001eq4hvc': 400,
 'cents': 789,
 'mindy': 2787,
 'ask': 349,
 'guys': 2036,
 'haha': 2042,
 'reputation': 3565,
 'chubby': 880,
 'habenero': 2038,
 'mini': 2789,
 'replaceable': 3554,
 'complexity': 1000,
 'wimp': 4773,
 'according': 144,
 'cramps': 1109,
 'stated': 4115,
 'chowing': 877,
 'folate': 1791,
 'stars': 4105,
 'pucker': 3388,
 'deterred': 1293,
 'united': 4585,
 'seeing': 3798,
 'advertised':

In [59]:
tf.idf_

array([5.6754955 , 6.92825847, 6.92825847, ..., 6.92825847, 6.23511129,
       6.92825847])

In [60]:
vector=tf.transform([X[999]])

In [61]:
vector

<1x4876 sparse matrix of type '<class 'numpy.float64'>'
	with 48 stored elements in Compressed Sparse Row format>

In [62]:
vector.shape

(1, 4876)

In [63]:
vector.toarray()

array([[0., 0., 0., ..., 0., 0., 0.]])

In [64]:
vector.data

array([0.12848085, 0.13646738, 0.07603529, 0.08185511, 0.07428327,
       0.07083224, 0.13646738, 0.13646738, 0.09431404, 0.13646738,
       0.13646738, 0.07847014, 0.12281432, 0.10476594, 0.12281432,
       0.10684125, 0.17847106, 0.06789666, 0.11482778, 0.11841901,
       0.11179144, 0.09212321, 0.0995981 , 0.11482778, 0.13646738,
       0.13646738, 0.10684125, 0.10684125, 0.09431404, 0.11179144,
       0.12848085, 0.13646738, 0.07899543, 0.15299755, 0.11179144,
       0.10916125, 0.09431404, 0.10476594, 0.08185511, 0.10117472,
       0.10684125, 0.08752165, 0.59485875, 0.07014104, 0.27636963,
       0.08923553, 0.11841901, 0.09111287])

# Hashing with HashingVectorizer

In [65]:
from sklearn.feature_extraction.text import HashingVectorizer

In [66]:
hv=HashingVectorizer()

In [67]:
hv

HashingVectorizer(alternate_sign=True, analyzer='word', binary=False,
         decode_error='strict', dtype=<class 'numpy.float64'>,
         encoding='utf-8', input='content', lowercase=True,
         n_features=1048576, ngram_range=(1, 1), non_negative=False,
         norm='l2', preprocessor=None, stop_words=None, strip_accents=None,
         token_pattern='(?u)\\b\\w\\w+\\b', tokenizer=None)

In [68]:
tf=HashingVectorizer(n_features=1000)

In [69]:
tf

HashingVectorizer(alternate_sign=True, analyzer='word', binary=False,
         decode_error='strict', dtype=<class 'numpy.float64'>,
         encoding='utf-8', input='content', lowercase=True,
         n_features=1000, ngram_range=(1, 1), non_negative=False,
         norm='l2', preprocessor=None, stop_words=None, strip_accents=None,
         token_pattern='(?u)\\b\\w\\w+\\b', tokenizer=None)

In [70]:
vector=tf.transform([X[999]])

In [71]:
vector.shape

(1, 1000)

In [72]:
vector.toarray()

array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.05832118,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        , -0.05832118,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.05832118,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0. 

In [73]:
%time tf.transform([X[999]])

CPU times: user 1.32 ms, sys: 165 µs, total: 1.48 ms
Wall time: 1.4 ms


<1x1000 sparse matrix of type '<class 'numpy.float64'>'
	with 69 stored elements in Compressed Sparse Row format>